const os = require('os')
console.log(os.constants)
console.log(os.freemem())
console.log(os.hostname())
console.log(os.loadavg())
console.log(os.release())
console.log(os.type())
console.log(os.totalmem())